### ISSUE TITLE
[YCQL sample app] YCQL sample app fails to connect to universe with client to node TLS config enabled

### ISSUE THREAD

**Issue by nmantrav2** [yugabyte/yb-sample-apps#56]
1. Create a universe with client to node TLS enabled
2. Execute YCQL sample app

Throw error:

java -jar yb-sample-apps.jar --workload CassandraSecondaryIndex --nodes 172.151.21.116:9042,172.151.39.88:9042,172.151.63.235:9042 --num_threads_read 1 --num_threads_write 1 --num_unique_keys 1000000000
1 [main] INFO com.yugabyte.sample.Main  - Starting sample app...
30 [main] INFO com.yugabyte.sample.common.CmdLineOpts  - Using a randomly generated UUID : 98087f8d-ab82-49ea-92eb-cc961d0653a4
35 [main] INFO com.yugabyte.sample.common.CmdLineOpts  - App: CassandraSecondaryIndex
35 [main] INFO com.yugabyte.sample.common.CmdLineOpts  - Run time (seconds): -1
35 [main] INFO com.yugabyte.sample.common.CmdLineOpts  - Adding node: 172.151.21.116:9042
36 [main] INFO com.yugabyte.sample.common.CmdLineOpts  - Adding node: 172.151.39.88:9042
36 [main] INFO com.yugabyte.sample.common.CmdLineOpts  - Adding node: 172.151.63.235:9042
36 [main] INFO com.yugabyte.sample.common.CmdLineOpts  - Num reader threads: 1, num writer threads: 1
36 [main] INFO com.yugabyte.sample.common.CmdLineOpts  - Num unique keys to insert: 1000000000
36 [main] INFO com.yugabyte.sample.common.CmdLineOpts  - Num keys to update: -1000000001
36 [main] INFO com.yugabyte.sample.common.CmdLineOpts  - Num keys to read: -1
36 [main] INFO com.yugabyte.sample.common.CmdLineOpts  - Value size: 0
36 [main] INFO com.yugabyte.sample.common.CmdLineOpts  - Restrict values to ASCII strings: false
36 [main] INFO com.yugabyte.sample.common.CmdLineOpts  - Perform sanity check at end of app run: false
36 [main] INFO com.yugabyte.sample.common.CmdLineOpts  - Table TTL (secs): -1
36 [main] INFO com.yugabyte.sample.common.CmdLineOpts  - Local reads: false
36 [main] INFO com.yugabyte.sample.common.CmdLineOpts  - Read only load: false
36 [main] INFO com.yugabyte.sample.common.CmdLineOpts  - CassandraSecondaryIndex non-transactional index
36 [main] INFO com.yugabyte.sample.common.CmdLineOpts  - CassandraSecondaryIndex batch write
108 [main] INFO com.yugabyte.sample.apps.AppBase  - Connecting with 4 clients to nodes: /172.151.21.116:9042,/172.151.39.88:9042,/172.151.63.235:9042
Exception in thread "main" com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /172.151.21.116:9042 (com.datastax.driver.core.exceptions.TransportException: [/172.151.21.116:9042] Channel has been closed), /172.151.63.235:9042 (com.datastax.driver.core.exceptions.TransportException: [/172.151.63.235:9042] Channel has been closed), /172.151.39.88:9042 (com.datastax.driver.core.exceptions.TransportException: [/172.151.39.88:9042] Channel has been closed))
	at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:292)
	at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:131)
	at com.datastax.driver.core.Cluster$Manager.negotiateProtocolVersionAndConnect(Cluster.java:1839)
	at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1752)
	at com.datastax.driver.core.Cluster.init(Cluster.java:216)
	at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:389)
	at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:368)
	at com.datastax.driver.core.Cluster.connect(Cluster.java:313)
	at com.yugabyte.sample.apps.AppBase.createCassandraClient(AppBase.java:329)
	at com.yugabyte.sample.apps.AppBase.getCassandraClient(AppBase.java:148)
	at com.yugabyte.sample.apps.AppBase.createTablesIfNeeded(AppBase.java:576)
	at com.yugabyte.sample.Main.run(Main.java:167)
	at com.yugabyte.sample.Main.main(Main.java:247)

**Comment by gurushant-yb** [comment]
@nmantrav2 : Please download the root certificate for the universe and pass the downloaded cert to the above command line ```  
 java -jar yb-sample-apps.jar --workload CassandraSecondaryIndex --nodes 172.151.21.116:9042,172.151.39.88:9042,172.151.63.235:9042 --num_threads_read 1 --num_threads_write 1 --num_unique_keys 1000000000 --ssl_cert <downloaded root crt file>
```
cc: @streddy-yb

**Comment by gurushant-yb** [comment]
@nmantrav2 : Please validate, functionality has been changed, now we are showing the command in pop up, the user has to copy the command and run. No need to download the certificate explicitly.

**Comment by nmantrav2** [comment]
Which build has this change?

**Comment by nmantrav2** [comment]
Verified.
